### ISSUE TITLE
Is there any document?

### ISSUE THREAD

**Issue by zsimple** [KilledByAPixel/LittleJS#10]
Thanks for your great job firstly.

But is there any document about LittleJS? I know demo is great way to learn new things, but it must be very comfortable if people can learn littlejs by tutorials like "Getting started", "make you first awesome little game", "api doc"...

**Comment by KilledByAPixel** [comment]
I just finished up the documentation, maybe you didn't see it.

[](https://killedbyapixel.github.io/LittleJS/docs/)

I don't have a tutorial yet but that's a good idea. Also will be adding more stuff like examples to the documentation now that it exists.
