### ISSUE TITLE
drawLine with WebGL, color not as expected 

### ISSUE THREAD

**Issue by AndreaPravato** [KilledByAPixel/LittleJS#100]
I am probably doing something wrong, but I am not getting the expected color when I draw lines using WebGL (param true);

When I try (tried this in platformer example)
```drawLine(posA, posB, .1, new Color(9,6,45,1), true)```
(or whatever other color specification), I get a line that does not have the expected color (where expected color in this case would be new Color(9,6,45,1) (that is a dark purple/blue; I am getting pale pink).

**Comment by KilledByAPixel** [comment]
Color values from 0 to 1 so yeah, that's going to be white.
