### ISSUE TITLE
Particle constructor colorEnd not optional

### ISSUE THREAD

**Issue by snowfrogdev** [KilledByAPixel/LittleJS#105]
Not a huge deal but the doc comments say that the colorEnd param is optional when in fact it must be passed in to the constructor to avoid a runtime exception.

![image](https://github.com/user-attachments/assets/841e23d2-ecff-4511-885e-fdbaf32a3fea)

**Comment by snowfrogdev** [comment]
And while we're there, the description of `sizeStart`, `sizeEnd`, `fadeRate` and `additive` seem to be wrong.

**Comment by KilledByAPixel** [comment]
Got it, thanks!

https://github.com/KilledByAPixel/LittleJS/commit/93206cf02025bcb74b63b61411050855ee287172
