### ISSUE TITLE
improve sound control

### ISSUE THREAD

**Issue by KilledByAPixel** [KilledByAPixel/LittleJS#106]
add master gain node for volume control
a way to pause sounds and music

**Comment by isacben** [comment]
Thanks for considering it!

**Comment by KilledByAPixel** [comment]
I added a master gain node!

no way to pause sound yet, that is a little trickier.

https://github.com/KilledByAPixel/LittleJS/commit/e9322c86775d16738fd1bb76d53c617c0cc1d621
