### ISSUE TITLE
Question: Tiles render direction unmatched.

### ISSUE THREAD

**Issue by beetaa** [KilledByAPixel/LittleJS#11]
@KilledByAPixel Hi Frank, when I try the engine with code:

```js
const mapData = [
  [0, -1, 1, -1, 1, -1, 0, -1],
  [0, 1, -1, -1, 1, -1, -1, 0],
  [-1, -1, 1, -1, 1, -1, 0, 0],
  [-1, -1, 1, -1, 1, -1, 0, 0],
  [-1, 1, -1, -1, 1, 1, -1, 0],
  [0, 1, -1, 0, -1, -1, -1, 2],
]

function gameInit() {
  defaultTileSize = vec2(64)

  initTileCollision(vec2(mapData[0].length, mapData.length))

  const tileLayer = new TileLayer(vec2(), tileCollisionSize, vec2(64))

  const pos = vec2()
  for (pos.x = tileCollisionSize.x; pos.x--;) {
    for (pos.y = tileCollisionSize.y; pos.y--;) {
      if (mapData[pos.y][pos.x] >= 0) setTileCollisionData(vec2(pos.x, pos.y), 1)
      const tileIndex = mapData[pos.y][pos.x]
      const direction = randInt(4)
      const isMirror = randInt(2) > 0 ? true : false
      const color = randColor()
      const data = new TileLayerData(tileIndex, direction, isMirror, color)
      tileLayer.setData(vec2(pos.x, pos.y), data)
    }
  }

  tileLayer.redraw()

  cameraPos = tileCollisionSize.scale(0.5)
  cameraScale = 64
}

function gameUpdate() {
  //
}

function gameUpdatePost() {
  //
}

function gameRender() {
  //
}

function gameRenderPost() {
  //
}

engineInit(gameInit, gameUpdate, gameUpdatePost, gameRender, gameRenderPost, 'tiles.png')
```
 which with `tiles.png` from [puzzle example](https://github.com/KilledByAPixel/LittleJS/tree/main/examples/puzzle)

![image](https://user-images.githubusercontent.com/5688224/140848377-58bbba79-e48b-4e2d-9a7f-97eb29fbd3ed.png)

I hopefully want the result like this:

![image](https://user-images.githubusercontent.com/5688224/140848592-390fb092-84b9-4926-85e1-dd494ddf4b4e.png)

but unfortunately, I got this:

![image](https://user-images.githubusercontent.com/5688224/140848810-d21278fa-e331-4925-a1ff-082140226409.png)

The problem(question) is, **the render result was flipped on Y axis** across the `mapData`. Is this the correct result?

Currently, I can get `picture 1` with tuning `setTileCollisionData(vec2(pos.x, pos.y), 1)` to `setTileCollisionData(vec2(pos.x, 5 - pos.y), 1)` and `tileLayer.setData(vec2(pos.x, pos.y), data)` to `tileLayer.setData(vec2(pos.x, 5 - pos.y), data)`.

Is there any native solutions? Thank you.

**Comment by KilledByAPixel** [comment]
Your data is actually stored upside down. It depends how you look at it of course, but normally we think of the positive y axis as pointing up like LittleJS, not down like array notation.

You can store your data however you want, so long as it gets into the right place. It looks like you've already figured out how to solve the problem.
