### ISSUE TITLE
groundObject glitch

### ISSUE THREAD

**Issue by adamfk** [KilledByAPixel/LittleJS#111]
In the platformer example (freshly cloned), sometimes the enemies oscillate between ground and not ground. Maybe every other frame. See gif below.

![ground-glitch](https://github.com/user-attachments/assets/1f8a805c-b43d-4403-8863-80812eb0b806)

All the regularly spawned enemies tend to work as expected, but if I use `e` to spawn a new enemy, it almost always gets stuck oscillating between ground and not ground.

Here's my modifications to show the issue.

```js
class Enemy extends GameObject 
{
    //...

    update()
    {
        //...

        if (!this.groundObject)
        {
            this.debugTextAboveMe("In the air");
        }
        else
        {
            this.debugTextBelowMe("ground");
        }
    }

    debugTextAboveMe(str) {
        debugText(str, this.pos.add(vec2(0,1)), 0.5);
    }

    debugTextBelowMe(str) {
        debugText(str, this.pos.add(vec2(0,-1)), 0.5);
    }
}
```

**Comment by KilledByAPixel** [comment]
Thank you for reporting this bug and adding a gif. I have reworked a small bit of code that was responsible for this and I think the bug is fixed. Let me know if this works for you.

https://github.com/KilledByAPixel/LittleJS/commit/143233756835ff68fe5324b816250555336c25e1

**Comment by KilledByAPixel** [comment]
also i just fixed the upside down debug text bug i had just caused a few days ago...

https://github.com/KilledByAPixel/LittleJS/commit/d494726feed6314195144cd57700de378367dea4

**Comment by adamfk** [comment]
Thanks! Will try it out tomorrow.

**Comment by adamfk** [comment]
works great. Thanks :) 🕹️ 🕹️ 🕹️
