### ISSUE TITLE
Issue refreshing glDrawing?

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#12]
I'm not sure if this is a bug, or I should be doing something I'm not.

I have an objectSpawner object, which renders a grid of tiles where you can place based on mouse position, which works like:

1) user clicks UI, and it creates a ObjectSpawner object, and stores a global reference to "objectSpawner", so I can update it when moving mouse etc
2)  this objectSpawner has a custom render function that does something like this:
for (var pl=0; pl < this.objectsData.length; pl++) {
        // draw above tileLayers where an object you have has certain range/grid coverage
        // get color, etc...
        drawTile(pos, this.drawSize, this.tileIndex, this.tileSize, this.color, this.angle, this.mirror);
 }

Now this all works fine generally speaking when I place the object properly (which destroyed the object, sets reference of objectSpawner = false and then, it setsData in tileLayers which renders those after), but there's an issue in a situation where user cancels placement, and tileLayers data isn't changed/refreshed (.destroy and reference are cleaned as well), and it apparantely doesn't cause a redraw of the gl layer, and leave the "grid of tiles" still rendered.

What is the correct way to "force a refresh" of the gl layer in such a situation?
I currently can do something like this to force a refresh, but it seems hacky at best - is there a more proper way to do this?

drawRect(vec2(1), 1, new Color(1,1,1,0), 0);

**Comment by KilledByAPixel** [comment]
Hi, I am a little confused about the question, can you post the code to repro the issue?

What do you mean by "force a refresh" of the gl layer?

**Comment by slosumo** [comment]
Sure, I've added the code below:

1) Basically say you have a class that extends the engineObject, which has a render function that uses i.e. drawTile() (or any other mainContext/gl render function)

2) Now create this object  (i.e. use createObject(vec2(5,5));

3) Now destroy this object using objectSpanwer.destroy();

The result:
This object's render will still stay on screen IF there is not other rendering being done to the mainContext/gl directly (drawText, drawRect, drawTile...)

You can replicate this quickly to use puzzle example code, and remove all the render code in gameRender and gameRenderPost, and then do steps 2 & 3

Essentially, if an object is destroyed, and nothing else is being rendered, the mainContext will not redraw I assume - but it should be.

`
let objectSpawner = false;
function createObject(pos) {
    objectSpawner = new GameObject(pos, vec2(1));
}
class GameObject extends EngineObject
{
    constructor(pos, size, tileIndex=-1, tileSize=defaultTileSize, angle=0, color)
    {
        if (!(color)) {
            color = randColor();
        }

        super(pos, size, tileIndex, tileSize, angle, color);
        this.isGameObject = 1;
        this.collideTiles = 0;
        this.gravityScale = 0;
    }

    update()
    {
        super.update();
    }

    render()
    {

        drawTile(this.pos.add(vec2(.5)), this.drawSize, -1, this.tileSize, new Color(1,1,0, 0.8), this.angle, this.mirror); // draw which tile it fits on
    }

    destroy() {
        super.destroy();
    }
}
`

**Comment by KilledByAPixel** [comment]
Hmm, that is weird though it seems to work fine for me. Here is the code I am using to to reproduce the issue. I am not seeing a problem though. Can you modify this code to cause the bug?

```
let objectSpawner = false;
function createObject(pos) {
    objectSpawner = new GameObject(pos, vec2(1));
}
class GameObject extends EngineObject
{
    constructor(pos, size, tileIndex=-1, tileSize=tileSizeDefault, angle=0, color)
    {
        if (!(color)) {
            color = randColor();
    }

        super(pos, size, tileIndex, tileSize, angle, color);
        this.isGameObject = 1;
        this.collideTiles = 0;
        this.gravityScale = 0;
    }

    update()
    {
        super.update();
    }

    render()
    {

        drawTile(this.pos.add(vec2(.5)), this.drawSize, -1, this.tileSize, new Color(1,1,0, 0.8), this.angle, this.mirror); // draw which tile it fits on
    }

    destroy() {
        super.destroy();
    }
}

function gameInit()
{
    cameraScale = 100;
}

function gameUpdate()
{
     createObject(vec2());
     objectSpawner.destroy();
}

function gameUpdatePost()
{

}

function gameRender()
{
  
}

function gameRenderPost()
{
}

// Startup LittleJS Engine
engineInit(gameInit, gameUpdate, gameUpdatePost, gameRender, gameRenderPost);
```

**Comment by slosumo** [comment]
That code indeed doesn't replicate the issue, as the object is not ever drawn as you destroy it immediately :)

Just try to create it from console (remove the gameUpdate code you have), and then just call objectSpawner.destroy() from the console as well, and it should replicate.

**Comment by KilledByAPixel** [comment]
Fixed! I was clearing the gl buffer at the wrong time, should be good now.
