### ISSUE TITLE
Support passing root DOM element to engineInit

### ISSUE THREAD

**Issue by bmingles** [KilledByAPixel/LittleJS#120]
It would be helpful for `engineInit` to support an optional parameter to specify the root DOM element to attach the canvas to. To maximize flexibility, this could support either a DOM element or a query selector string.

**Comment by KilledByAPixel** [comment]
all hooked up now in latest, let me know if that works ok for you! 

https://github.com/KilledByAPixel/LittleJS/blob/1f6e5a6d0adf92384ebf18a6ef4faa7061119506/src/engine.js#L119

**Comment by bmingles** [comment]
Works great. Thanks!

**Comment by KilledByAPixel** [comment]
Yes, to make it fit anywhere on the page, it is intended to be put on an iframe. =

For test purposed I have the 3 main demos running in iframes on this page...

https://killedbyapixel.github.io/LittleJS/examples/
