### ISSUE TITLE
Awful performance in FireFox

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#13]
*This is not really a massive issue, but more of a performance note/report.

I know you're probably aware that FF is not the most performant, but just wanted to point this out here, as it seems I can't get above 20-30 FPS in my game, and as the world scales it quickly drops, while Chrome maintains a steady 60 FPS at big worlds.

And to confirm it's not just my game causing issues, I have much worse performance allover the even simplest examples, and can't reach 60FPS in FF.

Is there anything to try and do at this stage to improve FF performance, or is it just not that great with Web GL?

Some Sprite stress tests below:

**Test1: (a decent mid range computer)**
FF max is FPS with just 400 sprites
FF constantly adding sprites reaches 30 FPS after 24k sprites
Chrome: 60 FPS up to 55k sprites
Chromes: reaches 30 FPS after adding 90k Sprites

Computer specs:
OS: Win 10 x64
CPU: AMD Ryzen 5 2600
RAM: 16 gig DDR4
Graphics: GTX 1050 Ti

**Test2: Mobile Phone (Huawei Lite 20):**
FF 60 FPS up to 2k sprites
FF constantly adding sprites reaches 30 FPS after 13k sprites
Chrome: 60 FPS up to 4k sprites
Chromes: reaches 30 FPS after adding 15k Sprites

**Comment by KilledByAPixel** [comment]
Thanks for the stats! Firefox is indeed way slower, and it's super annoying. Make sure you are using glOverlay = 1, that really helps with firefox.

[Try my game Space Huggers in firefox and let me know how it runs.](https://www.newgrounds.com/portal/view/819609) That game pushes the engine pretty far. I've played in many browsers including safari on my iphone and it runs pretty solid with a lot going on.

Unfortunately I've already done pretty much everything I can to address the problem. Though if anyone finds a way to speed it up I am all ears!

**Comment by slosumo** [comment]
Runs pretty terrible on this device in fullscreen 1080p, probably 5-10 FPS, without fullscreen does 10-15.
Note I've got a bit of clogged up computer & multitasking, so it takes away bit from it, but not a huge difference after a refresh either.

I'm not sure your engine does this by default on the tileLayer because of how tiles work, but when drawing on canvas and ensuring integers (rounded positions, widths, heights...) are provided to any canvas function/draws can do a quite a bit for performance. If I remember correctly, it added up to +30% in one of my previous games. Not all games would be fine with rounding that though, so it maybe could be provided as a setting to do that and always round parameters to ints when using canvas.

Anyway, not a big deal for now - when I get to performance I'll have a think and see if I can find anything to help.

**Comment by KilledByAPixel** [comment]
If you can investigate a way to fix the slowdown I'd be interested to hear what you find. I've already done a pretty deep dive as you can imagine but it's possible I missed something. May also help upgrading the engine to webgl2, right now it is still using webgl1. I'll have to run some tests on firefox to see if it is worth it.
