### ISSUE TITLE
Help using shaders 

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#16]
I'm having a bit of a hard time wrapping my head around of how I could apply shaders to a specific layer or all of the canvases based on time, to i.e. be able to continually animate something (for example waves on water tiles) without having to resort to sprite animations which would require redrawing that said layer every frame.

From what I've gathered so far:
- applying a shader to the glCanvas is super straightforward -> anything using GL rendering every frame will simply work with a shader (example of that hover object in example)
- applying shaders to tileLayer only works at the time when they are refreshed/redrawn (i.e. after I click to place an object, it redraws that tileLayer and applies the updated shader)

So if I currently have say water tiles on a tileLayer, and I'd like to use a shader every frame on it, it would require a tileLayer.redraw() every frame, which feels like an overkill. Do you have an idea how something like this would be best to achieve in the current state of the engine?

I assume your post-processing task when done would sort of allow someone to do this quite easily?

I'm attaching an example that modulates the Blue in the shader based on time. The hover grids are drawn on gl, and everything below is are tileLayers - as you can see they are not changing color, until  I place something on them (Which redraws those specific tiles):

https://user-images.githubusercontent.com/10269798/142209764-d3a263ad-bab0-406a-ac7c-d553f7183e21.mp4

**Comment by KilledByAPixel** [comment]
Hi, thank you for sharing your work, looks cool!

So, the reason it does not work like that is because rendering the tile layer is slow, at least on some browsers and mobile. The problem is caused by compositing the result of the gl render onto the 2d canvas.

The tile layer is rendered to an offscreen canvas as an image, but you need it to be a gl texture to apply a shader.

The easiest option is to break out those animated tiles into objects. Keep the non animated ones in the tile layer.

Another way is to mess with effect to achieve water rather then relying on animation. In the same way the platformer example has a sky behind it, your level has water behind it.

There are other ways to do this, but that would require you rework the graphics code and rework the engine a lot. The tile layer could have it's own gl context, and vertex cache for example.

**Comment by slosumo** [comment]
Thanks as always for the great insight!

I was hesitant to break everything into objects, as we'll have quite big maps (up to 100x100), that could have up to a few K tiles of water. But I just did a quick test on Chrome, and seems it should be fine to handle rendering 2-3k objects on gl. So maybe I'll just lay those where water is, and use a shader with them. Will give me some complexity with managing layers (as there's some tiles we place on top of water), but might not be too much.

I.e. quick stress example with animating 2-3k objects, runs pretty smooth:
https://user-images.githubusercontent.com/10269798/142406266-c48c8f01-2a1b-4709-b13e-665786c9ecf0.mp4

Not 100% sure I'll be able to mess with effects, as for our use case, the water kinda has to have neat transitions with neighboring tiles and it can appear inland as well.
I also might do some simple LoD, and just turn water to objects and animate it when more zoomed in, as that should typically not result in having more than 1k of water objects in viewport. 
Another idea I had - instead of maybe just drawing the 3k objects in gl, would maybe be to draw water in a separate tileLayer, then draw its full context on GL, and apply shader to it. That way, it'd just be rendering one big image, instead of 3k separate water draws.

To give you a better idea of what sort of effect I'm after:
Ideally something like this: https://forum.unity.com/threads/2d-water-flow-shader.784802/
As a minimum something like this: https://youtu.be/nG8OU1GwMtk?t=8

Anyway, you gave me some good pointers of what direction to go in, thanks :)

**Comment by KilledByAPixel** [comment]
You should be fine to have a few thousand objects animating. Though switching shaders may be expensive in some browsers.

The first link you show in unity is to demonstrate directed flow, do you have that in your game?

The second one might be more easily achieved without using a shader. It looks like a flipbook style animation would work fine.

You might also think about having the water layer transparent in the tiles, then below that do particle effects to simulate water. I think that could look really good, in some ways better then either of these and is much easier to do.

**Comment by slosumo** [comment]
Won't really have directed flow, but would try to get a similar animation going "ideally" i.e.  having some gradual/more random waves/water movement. The reason why I'm not immediately going for a flipbook animation, is because with a shader it removes a ton of requirements for a lot of artwork, as it'd have to cover a bunch (31 tile variations) if I also wanted to animate waves next to the shores.

I've got an idea of how to make that work with transparent water and shaders, so will see if I can make that work, otherwise your idea of using particles is an ingenious one! I'll give several of these a try - thanks for everything, really have a much better idea of the options now!
