### ISSUE TITLE
Drawing images from texture that are not following the "tileIndex rule"

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#17]
From what I've looked at this is currently unsupported, or at least can't see a "neat way" to draw an image from the texture, that is NOT following the tileSize and tileIndex "rules".

For example, say I do want to use tiles in most cases, but simply have some objects to draw which are much bigger than the tileSize (and the image has to be bigger, or even not a square, but rectangular (use case can only be inside render functions of objects, and no need to be supported usage by tileLayers).

How could I achieve this to use gl renderer, and be able to use "custom "tileImage spriteCut" parameters", i.e.:
sx ... x of which area of the texture to take
sy ... y ^^
sw ... w  ^^
sh ... h ^^

Would the simplest be to  adjust the drawTile tileIndex parameter, that if it's passed as object of sx,sy,sw,sh values, just calculate uvX, uvY differently? I'm not sure if that's all that's needed, as I didn't dive yet into what all the other params of bleed etc. mean.

Any help/point in the right direction much appreciated!

![texture_indexes_questions](https://user-images.githubusercontent.com/10269798/143075584-11becc34-be0d-4181-9382-c3983ef2f8c3.PNG)

**Comment by KilledByAPixel** [comment]
It is set up to do different sized tiles and non square tiles already.

You can do this by changing the tileSize. To get the tile index, you count from the top left using that tile size.

So for those larger tiles in your example, lets say they are 4x the tile size. If so, you need to move the red one over by the length of the orange square. Then it would be tile index 2 with that larger size.

There is a good example of this in the platformer example. The grenade and gun use smaller 8x8x tiles.

So here the circle is tile index 0. The gun and grenade are tile index 2 and 3 using an 8x8 size. The crate is also tile index 2 but with the default 16x16 tile size. Does that help?

![tiles2](https://user-images.githubusercontent.com/16227600/143088016-008afa34-0478-454f-95c3-f540907f889d.png)

**Comment by slosumo** [comment]
It does indeed help to some degree. But it still has the constraint of having the assets basically be in square holders, and makes getting images with rectangular (non-square) proportions difficult and quite a chore to set up the spritesheet in general as well.

Having this custom functionality just seems so needed for various types of games/situations, and I'll likely end up needing it in several situations - I'm just not sure if doing something like below, messes with how webGL works and would end up not working correctly - or is it as simple as this example and it should work?

```
function drawTileCustomSprite(pos, size=vec2(1), tileInfo = {sx: 0, sy: 0}, tileSize=tileSizeDefault, color=new Color, angle=0, mirror, 
    additiveColor=new Color(0,0,0,0), useWebGL=glEnable)
{
    showWatermark && ++drawCount;
    if (glEnable && useWebGL)
    {
        if (tileInfo === false|| !tileImage.width)
        {
            // if negative tile index or image not found, force untextured
            glDraw(pos.x, pos.y, size.x, size.y, angle, 0, 0, 0, 0, 0, color.rgbaInt()); 
        }
        else
        {
            // calculate uvs and render
            const cols = tileImageSize.x / tileSize.x |0;
            const uvSizeX = tileSize.x / tileImageSize.x;
            const uvSizeY = tileSize.y / tileImageSize.y;
            const uvX = tileInfo.sx, uvY = tileInfo.sy;
            
            glDraw(pos.x, pos.y, mirror ? -size.x : size.x, size.y, angle, 
                uvX + tileImageFixBleed.x, uvY + tileImageFixBleed.y, 
                uvX - tileImageFixBleed.x + uvSizeX, uvY - tileImageFixBleed.y + uvSizeY, 
                color.rgbaInt(), additiveColor.rgbaInt()); 
        }
    }
	.....
}

//usage example:

var spriteOffsets = { // just holds info about image positions & size on the sprite
	image_tag_1: {sx: 50, sy: 543, sw: 50, sh: 145}, 
	image_tag_2: {sx: 160, sy: 250, sw: 25, sh: 122}, 
	....
};

// draw image_tag_1
var spritePos = {sx: spriteOffsets.image_tag_1.sx, sy: spriteOffsets.image_tag_1.sy};
var tileSize = {x: spriteOffsets.image_tag_1.sw, y: spriteOffsets.image_tag_1.sh};
drawTileCustomSprite(pos, size(1), spritePos, tileSize);
```

**Comment by KilledByAPixel** [comment]
Tiles don't need to be square, they can have a different width and height. Though they do need to packed in a certain way in the texture. If the sprite is smaller then the containing rec, you can just make the rest alpha and center it in the rectangle.

Your code looks like it should work fine if that's how you prefer to do things.

Can you show me an example of a sprite you are using that needs custom rendering?

**Comment by slosumo** [comment]
Yeah that's the main issue - requiring certain/exact tiling - it's great in case of assets being more or less of same dimensions, but if there's a bunch of assets of diff dimensions to put on a sprite, it could be a pain to get things aligned correctly. Especially if using some sort of auto-sprite map generator, which can create sx,sy,sw,sh exports, it's much easier to just use those.

Sure -> I just put together a quick mockup prototype sprite to give you an idea of how different they can look - and there's going to be a ton more images of different proportions as well. 
![image](https://user-images.githubusercontent.com/10269798/143257887-c27fba1d-433a-45d1-8286-79aafb5fe912.png)

Or another example from google that's often typical from i.e. various premade bundles, or sprite generators that output sx,sy,sw,sh in a neat format for you to just use:
![image](https://user-images.githubusercontent.com/10269798/143258242-f710ca02-fa3b-4902-ad80-c01025c2c40b.png)

I'm essentially preparing a starting point for our other dev to recode another prototype to use littleJS, and in that game this sort of functionality simplifies a lot of things. Thanks, will try it out - still figuring out the little bits of the engine so awesome to have some quick feedback from you before getting lose in reinventing the wheel etc ;)

**Comment by KilledByAPixel** [comment]
I have found that tile sheets are easier to work with when things are placed neatly on a grid, but maybe that is not a standard.

For the 2nd sprite sheet, there is no way that will work here because the sprits are overlapping rectangular boundaries. Maybe this tile sheet was meant to be mapped to 3d objects.

I will think again about changing tileIndex to instead be a vec2 of the top left coord of the sprite in the sheet. I have been thinking about that for a while and it might make sense. What do you think about that option?

**Comment by slosumo** [comment]
Ah you're right, the second one is not a good example, as they're overlapping indeed.

I honestly think that the way it is now is great - and encourages people to use the engine in its most optimal form - and you're also likely wanting to keep the core engine minified as much as possible.

But I do think you should add certain extensions that are likely going to be commonly used (this is one example) that allow some flexibility - perhaps creating a file "engineExtensions.js" or something like that, where you could add such additional use cases, without forcing you to scale up your core code too much, but still offer a quick plug & play solution for utilities that'll certainly be useful to many?

**Comment by KilledByAPixel** [comment]
Yeah, I think you get the point of the engine. I try to keep everything as simple and small as possible. It works for most things, but for larger projects like yours I really expect people would want to change a few things to better suit the project.

The tile index thing is not for a perf boost but more to make it simpler to work with. So you can have similar sprites all together in the texture which makes it easier to work with in code.

But if you are working with an artist who exports from a sprite sheet program it would make sense to have another function that you can feed that sprite data into directly.

I like the idea of having some kind of extensions/plugins folder. That could work because I have other stuff I want to hook up that is outside the scope of the normal engine like box2d physics.

**Comment by slosumo** [comment]
Yeah I think with something like that it'll be much more approachable to a lot of devs as well - knowing there's some very useful extensions/plugins in an engine can be a big thing to get a bigger audience. I've sort of started doing something like this for our own use, kinda merging our own generalized code into the littleJS project but keeping it separate so I can easily update littleJS versions, so we got best of both worlds and be able to re-use stuff easily. At a later stage and when I can re-base some of this, I'll also commit some things that I think might be generally applicable.

![slika](https://user-images.githubusercontent.com/10269798/143269962-b56d33d4-f80f-480c-9f9d-572000e4cb3d.png)
