### ISSUE TITLE
Preventing render of objects outside gl canvas?

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#18]
Looking at the code I don't see any checks for engineObject rendering if they are visible inside the glCanvas.
Just wondering if this is something that's automatically detected by the renderer and if it's not, shouldn't it be built-in the engine for potential performance benefits? (assuming a game has objects that are not always visible)

Or perhaps adding an optional param to engineObject to not render when not visible?

**Comment by KilledByAPixel** [comment]
This is the kind of thing you need to hook up in your own custom object class.

It really depends on the game how much of a difference it will make, you will need to do some profiling. My guess is that for  most games it won't make any difference at all. You need to remember that checking if it is on screen requires work on the cpu, and skipping that step and letting the gpu handle it will likely help perf.

I'm sure there are cases where you are better off culling those objects manually, it's up to you.

**Comment by slosumo** [comment]
Makes sense - just wanted to mention it anyway in case it was a potential slipup. I know that canvas sort of ignores/isn't impacted much by offscreen rendering by itself, so probably something similar going on here that usually makes it not that bad.
