### ISSUE TITLE
Puzzle Game example doesn't check the tile boundary

### ISSUE THREAD

**Issue by lifthrasiir** [KilledByAPixel/LittleJS#2]
As result it is possible to swap a boundary tile with a wrong or even non-existent tile. For example, the following demonstrates that it is possible to swap the blue tile at (3, 0) with an imaginary tile at (3, -1), which is uninitialized and therefore interpreted as the zeroth color (red). The blue tile will then stuck at (3, -1).

![Before](https://user-images.githubusercontent.com/323836/135096973-0168f79f-1142-4ff4-9197-a16a543b98ac.png)
![After](https://user-images.githubusercontent.com/323836/135096983-016ecc0d-b624-40e2-87b7-db930792c309.png)

**Comment by KilledByAPixel** [comment]
Wow, good find! I think because there are actually tiles there waiting to fall. I will check in a fix soon.

**Comment by KilledByAPixel** [comment]
Just checked in a fix, now checking to make sure the mouse is a in a valid tile.
