### ISSUE TITLE
Use ES module or CommonJS ?

### ISSUE THREAD

**Issue by zhw2590582** [KilledByAPixel/LittleJS#21]
Thank you very much for providing this library, I am going to read the source code through Hello World, I know that you don't want to release NPM versions, each JS file is interactive through a lot of global variables, so it has caused a lot of doubts, which JS file from these global variables?

I think it will be easier to understand the principle of this library if we organize the code (such as import or require) in combination with the modularization of JS

**Comment by KilledByAPixel** [comment]
Hi, I am having trouble understating your request. It is on NPM. The engine is meant to all be included together. Though advanced users can pick it apart, there is no reason to do that. The files are split up to make things easier to navigate. You can just include the prebuild js file that has everything...

https://github.com/KilledByAPixel/LittleJS/blob/main/engine/engine.all.js

What benefits would wrapping this in modules have?

**Comment by dshepsis** [comment]
The main benefit to modularization would be to avoid global variables and make it easier to understand the flow of information by reading the source code. Currently, if I go to https://killedbyapixel.github.io/LittleJS/ and read `game.js`, I immediately see several globals: `Sound`, `Medal`, `initTileCollision`, `tileImage`, etc.. On the other hand, `Image` is a browser global from the DOM API. The naming scheme makes it difficult to know which is which without double checking. Finding where these global variables are declared requires searching and guessing, whereas if they were each imported from their corresponding modules, it would be clear.

**Comment by KilledByAPixel** [comment]
That sounds good in theory but in practice I am not sure where the actual confusion is. This is a small game engine that is not intended to be used modularly. Most modern game engines are developed with that paradigm but that would really work against the goals of this engine which is to keep things as simple and small as possible. I will continue to keep an open mind about it but it is not anything I plan on changing soon.

**Comment by KilledByAPixel** [comment]
Modules now fully supported and I added an example project that imports LittleJS as a module!

https://killedbyapixel.github.io/LittleJS/examples/module/
