### ISSUE TITLE
A bit of help with changing shaders appreciated

### ISSUE THREAD

**Issue by slosumo** [KilledByAPixel/LittleJS#24]
Hey,

So I'm finally getting around to changing shaders, and I'm able to do it if I just change it "for the whole app" on runtime, but if I try to change shaders for rendering specific objects (i.e. just water tiles), this doesn't work. Basically the browser just hangs, so I'm assuming I'm doing/reiniting something that I shouldn't be when changing shaders, but it's really not obvious to me -> this is first time I'm trying to use them so I'm probably missing something super obvious about how webGL works, any chance you could have a quick look at my below code?

From some webGL examples from what I understand when changing shaders after useProgram, buffers and vertexAttribs should be re-inited for the shared you're using, but it seems this is causing some sort of overkill when done hundreds of times per frame - do you see something obvious I should just need to remove/Change a bit to get this working? And sorry for wasting your time with what I assume are some of the webGL basics 😅 

```
//////// engineWebGL.js changes

let shaders = { // just defining some different shaders
	base: {
		vs: // vs1 string
		fs: // fs1 string
	}
	custom: {
		vs: // vs2 string
		fs: // fs2 string
	}	
};		
		
let customGLShader;
let usingShader = 0, glVertexData;

function initShaderVertextAttribArray() { // this is essentially moved from glInit, to be able to reinit when I change a shader

    // init buffers
    glCreateBuffer(gl_ARRAY_BUFFER, glVertexData.byteLength, gl_DYNAMIC_DRAW);

    // setup the vertex data array
    let offset =0;// glBatchCount = 0;
    const initVertexAttribArray = (shaderRef, name, type, typeSize, size, normalize=0)=>
    {
        const location = glContext.getAttribLocation(shaderRef, name);
        glContext.enableVertexAttribArray(location);
        glContext.vertexAttribPointer(location, size, type, normalize, gl_VERTEX_BYTE_STRIDE, offset);
        offset += size*typeSize;
    };

    let program = (usingShader === 0 ? glShader : customGLShader);
    initVertexAttribArray(program, 'p', gl_FLOAT, 4, 2);            // position
    initVertexAttribArray(program, 't', gl_FLOAT, 4, 2);            // texture coords
    initVertexAttribArray(program, 'c', gl_UNSIGNED_BYTE, 1, 4, 1); // color
    initVertexAttribArray(program, 'a', gl_UNSIGNED_BYTE, 1, 4, 1); // additiveColor
}

function glInit() {
	... //unchanged up to below point 

	// setup vertex and fragment shaders
	glShader = glCreateProgram(
		shaders.base.vs                      // end of shader
		,
		shaders.base.fs
		// end of shader
	);

	customGLShader =  glCreateProgram(
		shaders.custom.vs
		,
		shaders.custom.fs
	);

	glVertexData = new ArrayBuffer(gl_MAX_BATCH * gl_VERTICES_PER_QUAD * gl_VERTEX_BYTE_STRIDE);
	glPositionData = new Float32Array(glVertexData);
	glColorData = new Uint32Array(glVertexData);

	glBatchCount = 0;
	initShaderVertextAttribArray();
}
function glPreRender() {
	// everything is the same, instead of using glShader directly, its using this:
	
    let program = (usingShader === 0 ? glShader : customGLShader);
}



////// in-game changes:
function changeToShader(shaderName) {
    usingShader = shaderName;
    initShaderVertextAttribArray();
}


// When rendering an object, I just try to switch shader in a certain situation:

render() {
	if (this.tileIndex >= 256 && this.tileIndex < 320) { // change onyl for certain i.e. water tiles
		changeToShader(1);
	}
	// render stuff here
	
	
	if (this.tileIndex >= 256 && this.tileIndex < 320) {
		changeToShader(0); // change back to original/default shader
	}
}
```

**Comment by slosumo** [comment]
Edit -> I was able to sort of get 2 different shaders working without killing the browser, by simply initing vertexArray for both shader at the start, but with offsets adding up. They actually apply different shading, BUT they're not displaying correctly.
I assume this is the more appropriate direction to go in as I'm assuming there's just some small fix required here :)

![image](https://user-images.githubusercontent.com/10269798/145848047-dbc00af0-f663-4992-8903-08b9947152d6.png)

**Comment by KilledByAPixel** [comment]
Hey, that's cool you are digging into this! However this is a bit too much code for me to debug here. My suggestion would be go easy on the shaders, maybe there is an easier way?

If you really need to, you should combine the shaders into 1. Add another attribute that is a number that determines which type of shader to use, (0 is normal, 1 is water, maybe 2 is something else). Then you add that value as a parameter to glDraw. It will need to set this attribute on each vert and pass it through to the fragment shader. You should be able to get a simple test of that working (make it color red if the flag is on to test). This will render MUCH faster because you will never need to change the shader.

Let me know if that makes sense.

**Comment by slosumo** [comment]
It does make sense indeed, and a great idea! Will try this out tomorrow, thanks! This is exactly the sort of stuff I appreciate so much!

Right now, I look into some features(i.e. shaders) a bit every now and then as it's simply interesting, and something I think we'll "have to" use at some point anyway for best visual effects (be it water, or trees/grass movements etc,) - there's just things that seem "much easier" to do well if you can use shaders and know how to, especially without requiring additional art assets. But I'll definitely try without first - for example used some particles for some early water animation as you suggested, and even the first test is looking pretty decent. Just every now and then I like to break the routine & learn some new stuff and push the limits a bit 😅

**Comment by slosumo** [comment]
Just a final question here, if you don't mind:

I'm unsure how/where to store the vertex data here -< setting it to glPositionData, glColorData or glVertexData like below aren't working, and I can't find glColorData being used anywhere (or find documentation on it) to serve as an example.

![image](https://user-images.githubusercontent.com/10269798/145964130-b5c4100d-a108-4184-8560-ccd6ce6d9cec.png)
*I also changed gl_INDICIES_PER_VERT from 6 to 7, to account for this extra 1 size float.

If it's not clear to you immediately no need to bother, I'll just bugger off with this, and play around with some vanilla webGL to properly understand it first, before getting back to you about any shader related stuff.

**Comment by KilledByAPixel** [comment]
glPositionData and glColorData are both views into the same underlying data buffer glVertexData, just one is a float and one is a int. 

you need to update the vertex stride also to account for the extra data, a float is 4 bytes so you need to add 4.

just take it one step at a time and im sure you'll figure it out!

**Comment by slosumo** [comment]
Awesome, that cleared it up, thanks! Now I got the basics of specific shaders working, so should be enough to be able to start playing around with them :)


https://user-images.githubusercontent.com/10269798/146181015-f01deed7-7c41-4947-a5dd-b73af68559bf.mp4

**Comment by KilledByAPixel** [comment]
Nice work, looking good!

**Comment by slosumo** [comment]
Hey,
Got another question in case you might be able to give me a quick tip.
I'm using a bit of time and starting to figure shaders out: (got some sort of water effect almost working :D)
![shader_water_issue](https://user-images.githubusercontent.com/10269798/147467799-c1e8206b-feb7-4dd4-932a-3961e44807b3.gif)

... but for some effects I'd like need to get data about the current screenTexture & screenUV (i.e. to make a neat water refraction) - what is basically rendered on the glcanvas before the current draw call. I'm able to get the screenUV easily via a uniform, but unsure how/where to get that screenTexture.

Should I need to create and bind this texture (from glContext) in glPreRender each time (and pass it as a uniform), but for some reason that sounds like an overkill to me. Would that be the wrong way of doing it, and there's something else I'm missing?
