### ISSUE TITLE
Docs: search dropdown shows wrong return types for some functions

### ISSUE THREAD

**Issue by tbroadley** [KilledByAPixel/LittleJS#35]
For example, if I search for "utilities.abs" on https://killedbyapixel.github.io/LittleJS/docs/Input.html:

![image](https://user-images.githubusercontent.com/8731922/184555488-7ed55ce7-6bb7-4421-a0d2-4a86c8577a8c.png)

`abs` is listed as returning `undefined,` but it actually returns a Number.

**Comment by KilledByAPixel** [comment]
I noticed this too, not sure why because it seems to be set up correctly. I think it could be a problem with the doc generator I am using.

**Comment by KilledByAPixel** [comment]
seems to be working differently with new version of js docs, it does not show the type in search
