### ISSUE TITLE
uglify-js instead of uglifyjs package

### ISSUE THREAD

**Issue by glitchroy** [KilledByAPixel/LittleJS#4]
https://github.com/KilledByAPixel/LittleJS/blob/611fcd33ef6bc329b1e8354086647d1dd7d30d90/engine/buildSetup.bat#L4

I think the correct package is `uglify-js`, installing `uglifyjs` causes a deprecation warning and doesn't create a Windows executable, installing `uglify-js` does.

**Comment by KilledByAPixel** [comment]
thanks fixed!
