### ISSUE TITLE
Programmatically Triggering Inputs in LittleJS for Adaptive Gaming

### ISSUE THREAD

**Issue by squirelo** [KilledByAPixel/LittleJS#44]
Hello,

I'm currently working on a project that involves creating adaptive gaming tools using LittleJS as the engine. The goal is to demonstrate small games, such as a Space Invaders clone or your Space Huggers, that can be controlled via facial gestures or vocal commands.

My challenge is to programmatically emulate input events (e.g., key presses/releases) while maintaining the existing gamepad and keyboard functionality. Essentially, I need a way to trigger controls as if I were physically interacting with the keyboard, but via code.

Any advice or guidance on how to accomplish this would be greatly appreciated.

Thanks!

**Comment by squirelo** [comment]
To add a bit of context, I already tried many "obvious" solutions like KeyboardEvents, but nothing seems to works so that's why I end here by asking directly :)

**Comment by squirelo** [comment]
Ok got it, adding a bit of delay between press and release do the work. 

I spent 10h on this before filling this issue. Thx for the rubber ducking.

**Comment by KilledByAPixel** [comment]
Hey, glad you figured it out!

Another way to do this is to set the inputData array directly.
