### ISSUE TITLE
Tilde (~) for debug mode

### ISSUE THREAD

**Issue by jwigert** [KilledByAPixel/LittleJS#49]
Hi,

I'm using a Swedish keyboard layout, which makes it impossible for me to enter the debug mode using ~. The issue with ~ is that I need to press Alt Gr + a key which needs confirmation by me pressing the space key afterwords. This doesn't seem to work in Chrome or Firefox. To work around this, I just assigned a different key by editing the `debugUpdate` function. I was just wondering if you would consider assigning a different key by default to make it easier for users of non-U.S. keyboard layouts?

**Comment by KilledByAPixel** [comment]
Thank you for the bug report, yeah maybe we should change the button, I will look into it!

**Comment by thewrath** [comment]
On the French keyboard, we have the same issue. What about the "escape" key (code 27)?

If I'm right, this key exists and is directly accessible on all keyboard layouts ?

**Comment by KilledByAPixel** [comment]
Ok, I moved it to Esc to support the international community!

I added a 


Hopefully that works for everyone.
