### ISSUE TITLE
Unable to join discord

### ISSUE THREAD

**Issue by jwigert** [KilledByAPixel/LittleJS#53]
Hi, I'm unable to join the discord. I just get the message: "Whoops... Unable to accept invite". Maybe the invite has expired?

**Comment by KilledByAPixel** [comment]
here is a new link! https://discord.gg/zb7hcGkyZe

**Comment by jwigert** [comment]
I unfortunately still get the same error.

**Comment by KilledByAPixel** [comment]
Weird! Here it is again, I double checked that this is set to unlimited so it should definitely work.  If it doesn't work, maybe try restarting discord or something. 

https://discord.gg/zb7hcGkyZe

**Comment by KilledByAPixel** [comment]
OK that appears to be the same exact link, this is the only link it is giving me.

**Comment by jwigert** [comment]
Now it works! Seems to have been some issue with my session. It worked after login out and in again. Thanks!
