### ISSUE TITLE
Small error in tutorial

### ISSUE THREAD

**Issue by mrtrombone** [KilledByAPixel/LittleJS#58]
Working through breakout tutorial and all going well until section explaining debug.

Sentence currently reads:
Debug Display
**This is a good time to try opening up the debug info by pressing ~.** 

Tilde should be replaced by [esc] key  - Had to go diving into docs to find this out.

Tiny issue but thought it might be helpful to fix

Cheers

**Comment by KilledByAPixel** [comment]
Thanks so much for the report, fixed!

**Comment by mrtrombone** [comment]
No prob

The only other thing I picked up was suggesting resetting the score to zero
when you recreate the ball

Great library. Should be fun

Cheers
Mark
