### ISSUE TITLE
Pixel perfect on chrome

### ISSUE THREAD

**Issue by ClementCariou** [KilledByAPixel/LittleJS#59]
I noticed the render looks blurry on Chrome. 
The simplest way to fix it would be to add the following lines in the HTML files :
```html
<style>canvas{ image-rendering: pixelated; image-rendering: crisp-edges; }</style>
```
| Before   |  After  |
|---|---|
| ![image](https://github.com/KilledByAPixel/LittleJS/assets/37800288/4052825a-c913-4070-b3dc-b56c8eed5e17)  |  ![image](https://github.com/KilledByAPixel/LittleJS/assets/37800288/0e1f93b0-f856-485d-95e9-5f1af8880c25) |

But you might find a better way to fix it directly in the engine itself.

**Comment by KilledByAPixel** [comment]
Thanks for reporting this! It seems like it was working before because the canvas is the same size as the window, but something recently has caused a slight blur. I have it set to use image-rendering:pixelated now
