### ISSUE TITLE
VSCode intellisense

### ISSUE THREAD

**Issue by ClementCariou** [KilledByAPixel/LittleJS#64]
Hello,
I noticed VSCode intellisense doesn't always work.
![image](https://github.com/KilledByAPixel/LittleJS/assets/37800288/55efc2fb-8581-4f98-a28e-3e57c254db65)
Currently, the JSDoc employs more explicit argument names than the ones utilized in the function :
![image](https://github.com/KilledByAPixel/LittleJS/assets/37800288/566c9801-86c0-400b-9c50-454f55415139)

The following solutions can be considered :
 - Use the explicit name in the code
![image](https://github.com/KilledByAPixel/LittleJS/assets/37800288/26c8894f-ed15-467b-8064-72597f5c164d)
- Write the explicit name in the argument description
![image](https://github.com/KilledByAPixel/LittleJS/assets/37800288/bd384fb6-f639-40a4-92ea-d52e872bbf9b)

**Comment by KilledByAPixel** [comment]
thank you for noticing this. that makes sense, i see it too. will try to fix.

**Comment by KilledByAPixel** [comment]
Fixed! I think I got everything but possibly missed one. let me know if you see anything else, thanks!

https://github.com/KilledByAPixel/LittleJS/commit/b33f9356fe34da8e99d2a7cb3120a44127cb2cc2

**Comment by ClementCariou** [comment]
Thank you ! 😃
