### ISSUE TITLE
New LittleJS Logo

### ISSUE THREAD

**Issue by KilledByAPixel** [KilledByAPixel/LittleJS#70]
I am working on a new logo for LittleJS. Here are a few prototypes with help from AI for what I am thinking...

![1](https://github.com/KilledByAPixel/LittleJS/assets/16227600/4cb0f5b2-e0bb-43c8-8a20-d39e277b7208) ![44855](https://github.com/KilledByAPixel/LittleJS/assets/16227600/bdbd764c-2f9f-41b5-8c77-6a4ac2b90d86)
![OIG](https://github.com/KilledByAPixel/LittleJS/assets/16227600/c7464f3d-3407-4201-88c5-c752950f4ecd) ![13](https://github.com/KilledByAPixel/LittleJS/assets/16227600/3d280c6c-080b-48cd-8c63-3bbd302f35ec)

Which of these do you prefer? 

Or reply with your own ideas, any help is appreciated, thanks!

**Comment by KilledByAPixel** [comment]
Here are a few reference images I am using as inspiration...

The Little Engine That Could by Watty Piper 
Illustrated by Lois Lenski
![44855](https://github.com/KilledByAPixel/LittleJS/assets/16227600/23888316-fa65-4fc1-a189-8a73f0657184)

![3](https://github.com/KilledByAPixel/LittleJS/assets/16227600/eed58524-487d-412a-8cfc-ad71af2b4a4a)
![train](https://github.com/KilledByAPixel/LittleJS/assets/16227600/78b7fd88-c4b9-4a97-8759-1ca575651dd8)

How to draw trains by Ed Emberley
![il_794xN 2988808953_qd8n](https://github.com/KilledByAPixel/LittleJS/assets/16227600/10410733-e2a6-4d37-85dc-4d2d63a77338)

**Comment by KilledByAPixel** [comment]
![faviconBig2](https://github.com/KilledByAPixel/LittleJS/assets/16227600/db8b4cbd-13f5-4b53-bc66-23c75e1b6068)

**Comment by yuzhicheng22** [comment]
Hello! KilledByAPixel.
I like your LittleJs very much. I personally prefer the logo in the upper right corner, which is more simple. The other logos are a bit too complicated, but I also like the colorful colors of the logo in the upper left corner, which makes people feel very relaxed. It’s energetic, I think it would be perfect if these two logos could be combined!

**Comment by kgish** [comment]
Upper left hand corner is my choice.

**Comment by Lukenickerson** [comment]
Upper left looks like something out of a game made with littlejs (pixel-ly). The bottom ones are too 3d-looking. The top right is also good, but looks like vectors.

**Comment by KilledByAPixel** [comment]
![jam2e](https://github.com/KilledByAPixel/LittleJS/assets/16227600/6df960d0-60f7-442d-ba8c-275fbdea4dce)

How about something like this?

**Comment by KilledByAPixel** [comment]
another variation...
![logo9a](https://github.com/KilledByAPixel/LittleJS/assets/16227600/9c4111d5-a9c3-43cc-8c06-19ee7df9fc8c)

**Comment by KilledByAPixel** [comment]
I remade it in 100% JS and created a splash screen function for the game!

![littlejslogo (22) (5)](https://github.com/KilledByAPixel/LittleJS/assets/16227600/61508eba-22d1-486e-b15e-593c42676357)

**Comment by KilledByAPixel** [comment]
LittleJS logo is officially finished. Thank you everyone who helped by giving feedback. 🚂🎉

![littlejslogo333](https://github.com/KilledByAPixel/LittleJS/assets/16227600/f37d1d42-70c5-4b63-9ed8-c61fabe998df)

The philosophy of the engine inspired me to make the logo fully in code. This allowed for a special startup splash screen that can be enabled in any LittleJS game by setting `showSplashScreen=true`. There is even a cool little animation that plays to draw it, fully code driven of course. 😅👍

![littlejslogo (22) (8) (1)](https://github.com/KilledByAPixel/LittleJS/assets/16227600/6809b231-58df-43ed-808c-1d92bd706981)

Already hooked up in the demos! I also updated other places with the new logo where appropriate. I will continue to iterate but I think this is pretty close to final. Looking forward to seeing you all in the LittleJS game jam later this year!
