### ISSUE TITLE
Error in puzzles example

### ISSUE THREAD

**Issue by Sachin4219** [KilledByAPixel/LittleJS#73]
Hi, I was looking at the examples of little.js and i found a puzzles example that does not seem to work.

Below is a screenshot of the link i used and the error shown in console
![image](https://github.com/KilledByAPixel/LittleJS/assets/91952010/a462cbcc-47a3-43b4-89a1-93bdff8f90b4)

**Comment by KilledByAPixel** [comment]
thank you for the report! it should be fixed now.
