### ISSUE TITLE
Better multi texture support

### ISSUE THREAD

**Issue by KilledByAPixel** [KilledByAPixel/LittleJS#74]
Several users have mentioned wanting to use multiple tile sets. It would be good to think of a better way to handle rendering and loading of multiple files.

**Comment by zbagdzevicius** [comment]
+

**Comment by KilledByAPixel** [comment]
[We Have Multi Texture Support!
](https://github.com/KilledByAPixel/LittleJS/commit/fc46747c2a2450d10ffd94f33734d2e0b23f889d)

engineInit now takes an array of images to load instead of just one.
it waits for all images to load and stores info in textureInfos using the new TextureInfo class
- that also includes creating the webgl texture if necessary
- other info about each texture can be cached here
Drawing functions used to take a tile index and tile size, now they take a TileInfo object
- a new function tile() can be used to create this object and easily retrofit old code
- this object stores the pixel position and size of each tile for better control
- also a textureIndex can be passed in to use any texture!
webgl automatically will handle swapping out textures when necessary
- if textures are being swapped often each frame this may effect performance
all examples have been updated using the new system
- platformer example has been set up to use 2 textures
