### ISSUE TITLE
Missing `rand` method in RandomGenerator in littlejs.esm.js

### ISSUE THREAD

**Issue by Lukenickerson** [KilledByAPixel/LittleJS#76]
I believe the `float` method is supposed to be called `rand`. 

The `int` method (https://github.com/KilledByAPixel/LittleJS/blob/main/build/littlejs.esm.js#L652) calls a method named "rand" which doesn't exist. I believe this is the same as "float": https://github.com/KilledByAPixel/LittleJS/blob/main/build/littlejs.esm.js#L639

**Comment by KilledByAPixel** [comment]
Fixed! Will update build soon...

https://github.com/KilledByAPixel/LittleJS/commit/de0f9dac2e678e5df21915ae0bcc07404f3f9fb9
