### ISSUE TITLE
Make Cheatsheet for how to use LittleJS

### ISSUE THREAD

**Issue by KilledByAPixel** [KilledByAPixel/LittleJS#89]
This will be reference that will especially help new users.

[Raylib has a good example](https://www.raylib.com/cheatsheet/cheatsheet.html)

**Comment by thewrath** [comment]
Raylib's cheatsheet is handy, but simply presents functions without explaining the lib's internal dependencies and interactions. Given that it's not an object-oriented lib (unlike LittleJS), it's quite useful. For littleJS, which has a lot of implicit behavior (especially when using EngineObject), it's difficult to present a complete cheatsheet simply by giving the module methods.

On the other hand, I think a cookbook explaining how to perform some of the basic “actions” of a game engine would be a real help and would make it easier to understand the engine's philosophy (such as phaser or pixi offer).

**Comment by KilledByAPixel** [comment]
# [LitlteJS reference sheet is live!](https://github.com/KilledByAPixel/LittleJS/blob/main/reference.md)

It was good for me to go through all this, I cleaned up a few small things in the process. I hope this helps some people out!
