### ISSUE TITLE
little bug in tileinfo

### ISSUE THREAD

**Issue by ejamshidiasl** [KilledByAPixel/LittleJS#94]
Hello, i have 100x100 pixel art image and i want to make tileinfo from 4x4 part of this image. there is a bug in coordinates. for example: 
a tile from vec2(64,16) with size (4,4) cause small part of edges come inside. so i must do:
```javascript
tileInfo2 = new TileInfo(
    vec2(64.11, 16.205),
    vec2(4.1),
    1
  );
```

**Comment by KilledByAPixel** [comment]
Could this be because of tileFixBleedScale? This setting is a little less then half a pixel by default shrinks the tiles a tiny bit to prevent bleeding from neighboring tiles. You can try setting that to 0 to see if it fixes your problem.

**Comment by ejamshidiasl** [comment]
YES, change to 0 solved my problem. thank you
