### ISSUE TITLE
Collision grouping

### ISSUE THREAD

**Issue by KumaWang** [KilledByAPixel/LittleJS#95]
I now have bullets and a platform. Now I want to jump from the bottom of the platform to the top of the platform and I need the bullet to collide with this elf. How do I do collision grouping?

**Comment by KilledByAPixel** [comment]
Hey, good question! You have full control over what collides with what by overriding these functions in EngineObject: collideWithTile, collideWithTileRaycast, and collideWithObject. You can decide there whether to accept or reject collisions.

If you take a look at the platformer example the Character.collideWithTile, it has some special stuff for ladders and breaking blocks. The ladder thing is probably most relevant here. Though im not sure if the platform it is a tile or an object. But basically you check if you hit a platform, and if the character's y velocity is positive then you return false to ignore the collision.

Similarly if you want to prevent bullets from hitting the character that fired them, you can check in the bullet's collideWithObject and reject the collision if it is the owner of the weapon.

**Comment by KumaWang** [comment]
Sir, I have a online team developing a game editor. Are you interested in co-op develop with us? We have a complete code editor with language services, animation editor for UI design, map editor, native rhi with v8|wasm runtime and other content needed for game design.
![90e34163ce3193c6cfba0eac77a234f9](https://github.com/user-attachments/assets/49a30c3b-72c4-4671-b0e1-233986edb06b)
![87cf554afcebcd95887ac97496f7fcdb](https://github.com/user-attachments/assets/85f2437f-8048-4db3-a1d1-1a7289475ede)
![fcaad9f9db0632a6444ee2c99cbce7cb](https://github.com/user-attachments/assets/8c237b64-bcb6-4990-ba95-6f47c901808f)
![f67657d71425b10a5c46ea41da88fe60](https://github.com/user-attachments/assets/caa9a3d9-b7e5-48e7-9a3c-e9b6b2446cdc)
